version: "3.9"

services:
  scraper:
    restart: on-failure
    container_name: scraper
    build: .
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=dependencies
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - selenium

  focused_webapp:
    restart: always
    container_name: focused_webapp
    stdin_open: true
    tty: true
    build: ./webapp
    ports:
      - "4000:4000"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=dependencies
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    depends_on:
      - scraper
      - postgres
    volumes:
      - ./webapp:/webapp

  selenium:
    image: seleniarm/standalone-chromium:102.0.5005.61
    environment:
      START_XVFB: 'false'
      SE_NODE_MAX_SESSIONS: 5
      JAVA_OPTS: "-XX:ActiveProcessorCount=5"
      SE_NODE_OVERRIDE_MAX_SESSIONS: 5

  postgres:
    restart: always
    container_name: postgres-container
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=dependencies
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    expose:
      - "5432"

  react_client:
      build:
        context: ./client
        dockerfile: Dockerfile
      ports:
        - "3000:3000"
      depends_on:
        - focused_webapp
      volumes:
        - ./client/src:/usr/src/app/src

volumes:
  db-data:

