SPOTIFY_URL = 'https://developer.spotify.com/third-party-licenses#embedded-sdk-third-party-licenses'
DISCORD_URL = 'https://discord.com/licenses'
PORSCHE_URL = 'https://connect-store.porsche.com/licenses.txt'
ADOBE_URL = 'https://www.adobe.com/products/eula/third_party.html'
SLACK_URL = 'https://slack.com/libs/desktop'
SAMSUNG_URL = 'https://developer.samsung.com/open-source?location=us'
CISCO_URL = 'https://www.cisco.com/en/US/docs/security/csa/csa602/license/opensource_thirdparty.html'
META_URL = 'https://www.meta.com/legal/portal/third-party-notices/'
BROADCOM_URL = 'https://techdocs.broadcom.com/us/en/symantec-security-software/identity-security/identity-suite/14-4/third-party-license-acknowledgments.html'
CONFLUENT_URL = 'https://www.confluent.io/third_party_software/platform/'
GENERIC_URL = 'https://landscape.todogroup.org/'
APPLE_MAPS_URL='https://www.apple.com/legal/internet-services/maps/oss-acknowledgements/'
BOSCH_URL = 'https://developer.bosch.com/3rdpartylicenses.html'
SMARTSHEET_URL = 'https://www.smartsheet.com/legal/acknowledgements'
